(() => {
  'use strict';
  const data = window.TCRI_DATA;
  if (!data) throw new Error('Synthetic demo data is unavailable. Run data/generate.mjs once.');
  const $ = id => document.getElementById(id);
  const state = { page: 1, perPage: 6, selected: [], detail: null };
  const colors = ['#1e4eb7', '#c9472e', '#24734d'];
  const gradeClass = grade => grade >= 7 ? 'risk-high' : grade >= 5 ? 'risk-mid' : '';
  const movementText = movement => ({ deteriorated: '↑ 惡化', improved: '↓ 改善', stable: '— 持平' })[movement];
  const resizeCanvas = canvas => { const ratio = Math.max(1, window.devicePixelRatio || 1); const rect = canvas.getBoundingClientRect(); canvas.width = Math.round(rect.width * ratio); canvas.height = Math.round(rect.height * ratio); const ctx = canvas.getContext('2d'); ctx.setTransform(ratio, 0, 0, ratio, 0, 0); return { ctx, width: rect.width, height: rect.height }; };
  const line = (ctx, points, color) => { ctx.strokeStyle = color; ctx.lineWidth = 2.5; ctx.beginPath(); points.forEach((point, i) => i ? ctx.lineTo(...point) : ctx.moveTo(...point)); ctx.stroke(); };
  const filters = () => {
    const search = $('search').value.trim().toLowerCase(), grade = $('grade-filter').value, movement = $('movement-filter').value;
    return data.companies.filter(company => (!search || `${company.name} ${company.id}`.toLowerCase().includes(search)) && (grade === 'all' || String(company.grade) === grade) && (movement === 'all' || company.movement === movement));
  };
  const ordered = () => filters().sort((a, b) => { const order = $('sort').value; if (order === 'name') return a.name.localeCompare(b.name, 'zh-Hant'); if (order === 'change') return (b.grade - b.series.at(-2).grade) - (a.grade - a.series.at(-2).grade); return b[order] - a[order]; });
  const renderSummary = () => {
    const cards = [['總公司', data.companies.length, 'all'], ['需優先複核', data.companies.filter(c => c.grade >= 7).length, 'high'], ['近期惡化', data.companies.filter(c => c.movement === 'deteriorated').length, 'deteriorated'], ['訊號觸發', data.companies.filter(c => c.signals).length, 'signals']];
    $('summary').innerHTML = cards.map(([label, value, filter]) => `<article class="summary-card"><button type="button" data-summary="${filter}"><span>${label}</span><strong>${value}</strong></button></article>`).join('');
  };
  const renderList = () => {
    const list = ordered(), totalPages = Math.max(1, Math.ceil(list.length / state.perPage)); state.page = Math.min(state.page, totalPages);
    const visible = list.slice((state.page - 1) * state.perPage, state.page * state.perPage);
    $('company-rows').innerHTML = visible.length ? visible.map(c => `<tr><td><input class="check" type="checkbox" data-select="${c.id}" aria-label="加入 ${c.name} 比較" ${state.selected.includes(c.id) ? 'checked' : ''}></td><td><button class="company-button" data-detail="${c.id}">${c.name}<span class="code">${c.id}</span></button></td><td>${c.industry}</td><td><span class="pill ${gradeClass(c.grade)}">${c.grade}</span></td><td>${c.score.toFixed(1)}</td><td class="change-${c.movement === 'deteriorated' ? 'bad' : c.movement === 'improved' ? 'good' : 'stable'}">${movementText(c.movement)}</td><td class="${c.signals ? 'warning' : ''}">${c.signals ? `● ${c.signals} 點` : '—'}</td><td><button class="company-button" data-detail="${c.id}">查看走勢</button></td></tr>`).join('') : '<tr><td colspan="8">沒有符合目前條件的合成公司。</td></tr>';
    $('result-count').textContent = `${list.length} 家結果`;
    $('page-label').textContent = `${state.page} / ${totalPages}`; $('prev-page').disabled = state.page === 1; $('next-page').disabled = state.page === totalPages;
  };
  const drawAxes = (ctx, width, height, values, labels) => { const pad = { l: 39, r: 18, t: 18, b: 34 }, min = Math.floor(Math.min(...values) / 10) * 10, max = Math.ceil(Math.max(...values) / 10) * 10 || 10; const x = i => pad.l + i * (width - pad.l - pad.r) / (labels.length - 1), y = v => pad.t + (max - v) * (height - pad.t - pad.b) / (max - min || 1); ctx.font = '11px Arial'; ctx.fillStyle = '#6b6961'; ctx.strokeStyle = '#ded7ca'; ctx.lineWidth = 1; for (let value = min; value <= max; value += 10) { ctx.beginPath(); ctx.moveTo(pad.l, y(value)); ctx.lineTo(width - pad.r, y(value)); ctx.stroke(); ctx.fillText(value, 6, y(value) + 4); } labels.forEach((label, i) => { if (i % 2 === 0) ctx.fillText(label.replace('20',''), x(i) - 14, height - 11); }); return { x, y }; };
  const drawTrend = company => { const canvas = $('trend-chart'), { ctx, width, height } = resizeCanvas(canvas), values = company.series.map(p => p.score), axes = drawAxes(ctx, width, height, values, data.quarters); line(ctx, company.series.map((p, i) => [axes.x(i), axes.y(p.score)]), '#1e4eb7'); company.series.forEach((point, i) => { if (point.alert) { ctx.fillStyle = '#c9472e'; ctx.beginPath(); ctx.arc(axes.x(i), axes.y(point.score), 5, 0, Math.PI * 2); ctx.fill(); } }); };
  const drawCompare = () => { const canvas = $('compare-chart'), chosen = state.selected.map(id => data.companies.find(c => c.id === id)).filter(Boolean), { ctx, width, height } = resizeCanvas(canvas); ctx.clearRect(0, 0, width, height); if (!chosen.length) { ctx.fillStyle = '#6b6961'; ctx.font = '13px Arial'; ctx.fillText('從清單勾選公司開始比較', 16, 32); $('compare-legend').innerHTML = ''; return; } const values = chosen.flatMap(c => c.series.map(p => p.score)), axes = drawAxes(ctx, width, height, values, data.quarters); chosen.forEach((company, i) => line(ctx, company.series.map((p, q) => [axes.x(q), axes.y(p.score)]), colors[i])); $('compare-legend').innerHTML = chosen.map((c, i) => `<span class="legend-item"><i class="legend-swatch" style="background:${colors[i]}"></i>${c.name}</span>`).join(''); };
  const renderCompare = () => { const chosen = state.selected.map(id => data.companies.find(c => c.id === id)).filter(Boolean); $('selected-chips').innerHTML = chosen.length ? chosen.map(c => `<span class="chip">${c.name}<button type="button" data-remove="${c.id}" aria-label="移除 ${c.name}">×</button></span>`).join('') : '<span class="empty">尚未選擇公司</span>'; drawCompare(); };
  const showDetail = id => { const company = data.companies.find(c => c.id === id); if (!company) return; state.detail = id; $('detail-panel').hidden = false; $('detail-title').textContent = `${company.name} · 信用風險趨勢`; $('detail-stats').innerHTML = [['目前分級', company.grade], ['風險分數', company.score.toFixed(1)], ['預警訊號', `${company.signals} 點`], ['合成營收', `${company.revenue} 億`]].map(([label, value]) => `<div class="stat"><span>${label}</span><strong>${value}</strong></div>`).join(''); $('detail-copy').textContent = company.signals ? '近期合成序列出現預警訊號，建議將財務槓桿與流動性指標列入優先複核。' : '合成序列未顯示近期預警點；仍應持續觀察後續財務更新。'; drawTrend(company); $('detail-panel').scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' }); };
  const setup = () => { for (let grade = 1; grade <= 9; grade++) $('grade-filter').insertAdjacentHTML('beforeend', `<option value="${grade}">第 ${grade} 級</option>`); ['search','grade-filter','movement-filter','sort'].forEach(id => $(id).addEventListener('input', () => { state.page = 1; renderList(); })); $('clear-filters').addEventListener('click', () => { $('search').value = ''; $('grade-filter').value = 'all'; $('movement-filter').value = 'all'; $('sort').value = 'risk'; state.page = 1; renderList(); }); $('prev-page').addEventListener('click', () => { state.page--; renderList(); }); $('next-page').addEventListener('click', () => { state.page++; renderList(); }); $('summary').addEventListener('click', event => { const f = event.target.closest('[data-summary]')?.dataset.summary; if (!f) return; $('grade-filter').value = f === 'high' ? '7' : 'all'; $('movement-filter').value = f === 'deteriorated' ? 'deteriorated' : 'all'; if (f === 'signals') $('sort').value = 'risk'; state.page = 1; renderList(); }); document.addEventListener('click', event => { const detail = event.target.closest('[data-detail]')?.dataset.detail, remove = event.target.closest('[data-remove]')?.dataset.remove; if (detail) showDetail(detail); if (remove) { state.selected = state.selected.filter(id => id !== remove); renderList(); renderCompare(); } }); document.addEventListener('change', event => { if (!event.target.matches('[data-select]')) return; const id = event.target.dataset.select; if (event.target.checked) { if (state.selected.length >= 3) { event.target.checked = false; alert('最多可比較 3 家公司。'); return; } state.selected.push(id); } else state.selected = state.selected.filter(item => item !== id); renderList(); renderCompare(); }); $('clear-compare').addEventListener('click', () => { state.selected = []; renderList(); renderCompare(); }); $('close-detail').addEventListener('click', () => { $('detail-panel').hidden = true; }); window.addEventListener('resize', () => { drawCompare(); if (state.detail) drawTrend(data.companies.find(c => c.id === state.detail)); }); renderSummary(); renderList(); renderCompare(); };
  setup();
})();
